### ISSUE TITLE
Don't show "NaN days ago"

### ISSUE THREAD

**Issue by dpoeschl** [dpoeschl/StashPop#63]
![image](https://cloud.githubusercontent.com/assets/235241/11818688/9b32ff6a-a310-11e5-9b6b-b19d4fb8a8a9.png)

**Comment by dpoeschl** [comment]
Needs repro.

**Comment by dpoeschl** [comment]
This may manifest differently now that we're using moment.js. If it crops up again, we can use that repro to investigate a fix. Closing for now.

**Comment by akoeplinger** [comment]
I still see this with moment.js, e.g. on https://github.com/mono/mono/pull/2372:

![image](https://cloud.githubusercontent.com/assets/1376924/11919881/71ea1ec0-a75e-11e5-8a1a-2ee8d183892f.png)

I looked with the debugger and `timestamp` in content.js:370 is `"20.12.2015 11:46:14"` (i.e. a localized string instead of English, afaik Jenkins uses the browser's language by default) so it can't parse it.

Did you think about using the Jenkins API instead of scraping the HTML ?

**Comment by akoeplinger** [comment]
I made a PR that fixes the issue: https://github.com/dpoeschl/StashPop/issues/68
